//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GVGCart
{
    public int ID { get; set; }
    public string CustomerId { get; set; }
    public int GpuID { get; set; }
    public int AmountCost { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public bool ItemsInCart { get; set; }

    public virtual Product Product { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.GVGCarts = new HashSet<GVGCart>();
        this.ProductSpecs = new HashSet<ProductSpec>();
    }

    public int Id { get; set; }
    public int GpuId { get; set; }
    public string GpuName { get; set; }
    public Nullable<int> Price { get; set; }
    public string Descriptionofgpu { get; set; }
    public string Image { get; set; }
    public string CustomerId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<GVGCart> GVGCarts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductSpec> ProductSpecs { get; set; }
}

public partial class ProductSpec
{
    public int Id { get; set; }
    public int GpuId { get; set; }
    public string BaseClock { get; set; }
    public string BoostClock { get; set; }
    public string VramMemory { get; set; }
    public string VideoOutput { get; set; }
    public string GpuName { get; set; }

    public virtual Product Product { get; set; }
}
